// src/components/installations/services/FatSatPdfExportService.ts
// EPEDE — Automated FAT/SAT PDF Generation Service
// Generates multi-page CEI 61439 / NF C 15-100 compliance reports with digital signatures
// Uses jsPDF + jspdf-autotable

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { InspectionCheckItem, InspectionStage } from '../ProjectCommissioningFatSatEngine';
import type { InstallationProject } from '../data/installationProjectModel';
import { computeProjectPowerBalance } from '../data/installationProjectModel';

// ─── Color Palette (EPEDE Engineering Brand) ────────────────────────────────
const COLORS = {
  obsidian:     [3, 7, 18]        as [number, number, number],
  deepSlate:    [15, 23, 42]      as [number, number, number],
  slate800:     [30, 41, 59]      as [number, number, number],
  slate600:     [71, 85, 105]     as [number, number, number],
  slate400:     [148, 163, 184]   as [number, number, number],
  slate200:     [226, 232, 240]   as [number, number, number],
  white:        [255, 255, 255]   as [number, number, number],
  emerald:      [16, 185, 129]    as [number, number, number],
  emeraldDark:  [6, 95, 70]       as [number, number, number],
  rose:         [244, 63, 94]     as [number, number, number],
  amber:        [245, 158, 11]    as [number, number, number],
  cyan:         [6, 182, 212]     as [number, number, number],
  gold:         [212, 175, 55]    as [number, number, number],
  // Subtle tones for tables
  rowEven:      [248, 250, 252]   as [number, number, number],
  rowPass:      [236, 253, 245]   as [number, number, number],
  rowFail:      [255, 241, 242]   as [number, number, number],
  rowPending:   [255, 251, 235]   as [number, number, number],
  headerBg:     [15, 23, 42]      as [number, number, number],
};

// ─── Helpers ────────────────────────────────────────────────────────────────

function rgbStr(c: [number, number, number]): string {
  return `rgb(${c[0]},${c[1]},${c[2]})`;
}

function setFillColor(doc: jsPDF, c: [number, number, number]) {
  doc.setFillColor(c[0], c[1], c[2]);
}

function setTextColor(doc: jsPDF, c: [number, number, number]) {
  doc.setTextColor(c[0], c[1], c[2]);
}

function setDrawColor(doc: jsPDF, c: [number, number, number]) {
  doc.setDrawColor(c[0], c[1], c[2]);
}

function pageWidth(doc: jsPDF): number {
  return doc.internal.pageSize.getWidth();
}

function pageHeight(doc: jsPDF): number {
  return doc.internal.pageSize.getHeight();
}

/** Draws the EPEDE header bar on top of each page */
function drawPageHeader(
  doc: jsPDF,
  title: string,
  projectRef: string,
  pageNum: number,
  totalPages: number,
) {
  const w = pageWidth(doc);

  // Dark header background
  setFillColor(doc, COLORS.deepSlate);
  doc.rect(0, 0, w, 22, 'F');

  // Accent stripe
  setFillColor(doc, COLORS.gold);
  doc.rect(0, 22, w, 1.2, 'F');

  // EPEDE wordmark
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  setTextColor(doc, COLORS.gold);
  doc.text('EPEDE', 10, 9);

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  setTextColor(doc, COLORS.slate400);
  doc.text('Electrical Power Engineering Digital Environment', 10, 15);

  // Page title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  setTextColor(doc, COLORS.white);
  doc.text(title, w / 2, 12, { align: 'center' });

  // Ref + page
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  setTextColor(doc, COLORS.slate400);
  doc.text(projectRef, w - 10, 9, { align: 'right' });
  doc.text(`Page ${pageNum} / ${totalPages}`, w - 10, 15, { align: 'right' });
}

/** Draws a thin footer bar at the bottom of each page */
function drawPageFooter(doc: jsPDF, locale: 'fr' | 'en') {
  const w = pageWidth(doc);
  const h = pageHeight(doc);

  setFillColor(doc, COLORS.slate800);
  doc.rect(0, h - 10, w, 10, 'F');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  setTextColor(doc, COLORS.slate400);

  const left = locale === 'fr'
    ? 'Document généré automatiquement par EPEDE — Usage technique interne'
    : 'Auto-generated by EPEDE — For technical use only';

  const right = locale === 'fr'
    ? `Normes : CEI 61439-1/2 · NF C 15-100 · CEI 60364-6`
    : `Standards: IEC 61439-1/2 · NF C 15-100 · IEC 60364-6`;

  doc.text(left, 10, h - 4);
  doc.text(right, w - 10, h - 4, { align: 'right' });
}

/** Section heading with color bar */
function drawSectionHeading(
  doc: jsPDF,
  text: string,
  y: number,
  color: [number, number, number] = COLORS.slate800,
): number {
  const w = pageWidth(doc);

  setFillColor(doc, color);
  doc.rect(10, y, w - 20, 7, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  setTextColor(doc, COLORS.white);
  doc.text(text.toUpperCase(), 14, y + 5);

  return y + 9;
}

/** Small KPI box */
function drawKpiBox(
  doc: jsPDF,
  x: number, y: number, w: number, h: number,
  label: string, value: string,
  valueFontSize: number,
  valueColor: [number, number, number],
  bgColor: [number, number, number],
) {
  setFillColor(doc, bgColor);
  setDrawColor(doc, COLORS.slate600);
  doc.roundedRect(x, y, w, h, 2, 2, 'FD');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  setTextColor(doc, COLORS.slate400);
  doc.text(label, x + w / 2, y + 6, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(valueFontSize);
  setTextColor(doc, valueColor);
  doc.text(value, x + w / 2, y + h - 5, { align: 'center' });
}

/** Horizontal key–value row */
function drawKV(
  doc: jsPDF,
  x: number, y: number,
  label: string, value: string,
  valueColor?: [number, number, number],
): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  setTextColor(doc, COLORS.slate600);
  doc.text(label, x, y);

  doc.setFont('helvetica', 'normal');
  setTextColor(doc, valueColor || COLORS.obsidian);
  doc.text(value, x + 52, y);

  return y + 5.5;
}

/** Status pill rectangle */
function drawStatusPill(doc: jsPDF, x: number, y: number, status: 'PASS' | 'FAIL' | 'PENDING') {
  const colors: Record<typeof status, [number, number, number]> = {
    PASS:    [16, 185, 129],
    FAIL:    [244, 63, 94],
    PENDING: [245, 158, 11],
  };
  const labels: Record<typeof status, string> = {
    PASS:    'PASS ✓',
    FAIL:    'FAIL ✗',
    PENDING: 'PENDING',
  };

  setFillColor(doc, colors[status]);
  doc.roundedRect(x, y - 3.5, 18, 5, 1.5, 1.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(5.5);
  setTextColor(doc, COLORS.white);
  doc.text(labels[status], x + 9, y, { align: 'center' });
}

// ─── Payload type ─────────────────────────────────────────────────────────────

export interface FatSatPdfPayload {
  project: InstallationProject;
  locale: 'fr' | 'en';
  stage: InspectionStage;
  checklist: InspectionCheckItem[];
  // Measured test values
  ratedUiVolts: number;
  ratedUimpKv: number;
  measuredRisoMegaOhms: number;
  measuredRpeMilliOhms: number;
  dielectricWithstandSec: number;
  appliedDielectricKv: number;
  requiredDielectricVoltageKv: number;
  busbarBoltSize: 'M8' | 'M10' | 'M12' | 'M16';
  recommendedTorqueNm: number;
  // Sign-off
  signerName?: string;
  signerRole?: string;
  inspectionBureau?: string;
  revisionRef?: string;
}

// ─── Main PDF generation entry point ─────────────────────────────────────────

export function generateFatSatPdf(payload: FatSatPdfPayload): void {
  const {
    project,
    locale,
    stage,
    checklist,
    ratedUiVolts,
    ratedUimpKv,
    measuredRisoMegaOhms,
    measuredRpeMilliOhms,
    dielectricWithstandSec,
    appliedDielectricKv,
    requiredDielectricVoltageKv,
    busbarBoltSize,
    recommendedTorqueNm,
    signerName = 'Ing. M. Touré (EUR ING)',
    signerRole = locale === 'fr' ? 'Ingénieur Responsable Essais' : 'Lead Commissioning Engineer',
    inspectionBureau = 'CONSUEL / Bureau Veritas',
    revisionRef = 'REV-A',
  } = payload;

  const isFr = locale === 'fr';
  const balance = computeProjectPowerBalance(project);
  const tgbtCurrentA = Math.round(balance.tgbtIncomerAmperes || 630);

  const passCount   = checklist.filter(c => c.status === 'PASS').length;
  const failCount   = checklist.filter(c => c.status === 'FAIL').length;
  const pendingCount = checklist.filter(c => c.status === 'PENDING').length;
  const totalCount  = checklist.length;
  const compliancePct = Math.round((passCount / totalCount) * 100);

  const isInsulationCompliant = measuredRisoMegaOhms >= 1.0;
  const isBondingCompliant    = measuredRpeMilliOhms <= 100;
  const isDielectricCompliant = appliedDielectricKv >= requiredDielectricVoltageKv;
  const isApproved = failCount === 0 && pendingCount === 0 && isInsulationCompliant && isBondingCompliant;

  const stageLabels: Record<InspectionStage, string> = {
    FAT:             isFr ? 'FAT — Essais d\'Atelier Constructeur (CEI 61439-1 §10)' : 'FAT — Factory Acceptance Testing (IEC 61439-1 §10)',
    SAT:             isFr ? 'SAT — Essais de Réception sur Site (NF C 15-100 Pt. 6)' : 'SAT — Site Acceptance Testing (NF C 15-100 Part 6)',
    PERIODIC_CONSUEL: isFr ? 'Audit Réglementaire Périodique — Visa CONSUEL' : 'Periodic Regulatory Inspection — CONSUEL',
  };

  const today = new Date().toLocaleDateString(isFr ? 'fr-FR' : 'en-GB', {
    day: '2-digit', month: 'long', year: 'numeric'
  });
  const refCode = `PV-${project.id.toUpperCase()}-${stage}-${revisionRef}`;
  const projectRef = `Réf: ${refCode}`;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const TOTAL_PAGES = 4;

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 1 — Cover Sheet & Project Identification
  // ══════════════════════════════════════════════════════════════════════════
  let yPos = 0;

  drawPageHeader(doc, isFr ? 'PROCÈS-VERBAL DE RÉCEPTION TECHNIQUE' : 'TECHNICAL COMMISSIONING CERTIFICATE', projectRef, 1, TOTAL_PAGES);
  drawPageFooter(doc, locale);

  yPos = 32;

  // Large cover title block
  setFillColor(doc, COLORS.deepSlate);
  doc.roundedRect(10, yPos, pageWidth(doc) - 20, 42, 3, 3, 'F');

  // Gold accent bar
  setFillColor(doc, COLORS.gold);
  doc.rect(10, yPos, 3, 42, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  setTextColor(doc, COLORS.white);
  doc.text(isFr ? 'PROCÈS-VERBAL D\'ESSAIS ET RÉCEPTION' : 'COMMISSIONING & ACCEPTANCE CERTIFICATE', pageWidth(doc) / 2, yPos + 12, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  setTextColor(doc, COLORS.cyan);
  doc.text(stageLabels[stage], pageWidth(doc) / 2, yPos + 22, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  setTextColor(doc, COLORS.slate400);
  doc.text(project.name, pageWidth(doc) / 2, yPos + 32, { align: 'center' });
  doc.text(`${refCode} — ${today}`, pageWidth(doc) / 2, yPos + 39, { align: 'center' });

  yPos += 50;

  // 4 KPI boxes: Compliance %, Status, Riso, Rpe
  const kpiW = (pageWidth(doc) - 20 - 9) / 4;
  const kpiY = yPos;

  drawKpiBox(doc, 10, kpiY, kpiW, 22, isFr ? 'TAUX DE CONFORMITÉ' : 'COMPLIANCE RATE',
    `${compliancePct}%`, 18,
    compliancePct === 100 ? COLORS.emerald : COLORS.amber,
    COLORS.rowEven);

  drawKpiBox(doc, 10 + kpiW + 3, kpiY, kpiW, 22, isFr ? 'DÉCISION RÉCEPTION' : 'COMMISSIONING STATUS',
    isApproved ? (isFr ? 'CONFORME' : 'APPROVED') : (isFr ? 'RÉSERVES' : 'PENDING'), 10,
    isApproved ? COLORS.emerald : COLORS.rose,
    COLORS.rowEven);

  drawKpiBox(doc, 10 + (kpiW + 3) * 2, kpiY, kpiW, 22, `Riso (req. ≥ 1 MΩ)`,
    `${measuredRisoMegaOhms} MΩ`, 14,
    isInsulationCompliant ? COLORS.emerald : COLORS.rose,
    COLORS.rowEven);

  drawKpiBox(doc, 10 + (kpiW + 3) * 3, kpiY, kpiW, 22, `Rpe (req. ≤ 100 mΩ)`,
    `${measuredRpeMilliOhms} mΩ`, 14,
    isBondingCompliant ? COLORS.emerald : COLORS.rose,
    COLORS.rowEven);

  yPos += 30;

  // ── Section: Project Identification ────────────────────────────────────────
  yPos = drawSectionHeading(doc, isFr ? '1. Identification du Projet' : '1. Project Identification', yPos);
  yPos += 3;

  const col1X = 12;
  const col2X = 110;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);

  let yLeft = yPos;
  let yRight = yPos;

  yLeft = drawKV(doc, col1X, yLeft, isFr ? 'Intitulé du Projet :' : 'Project Name:', project.name);
  yLeft = drawKV(doc, col1X, yLeft, isFr ? 'Type d\'Environnement :' : 'Environment Type:', project.environmentType);
  yLeft = drawKV(doc, col1X, yLeft, isFr ? 'Régime de Neutre :' : 'Earthing System:', project.supplyContext.earthingSystem);
  yLeft = drawKV(doc, col1X, yLeft, isFr ? 'Tension Nominale :' : 'Nominal Voltage:', `${project.supplyContext.nominalVoltageV || 400} V AC 50 Hz Triphasé`);
  yLeft = drawKV(doc, col1X, yLeft, isFr ? 'Transformateur HTA/BT :' : 'HV/LV Transformer:', `${project.supplyContext.transformerRatingKva} kVA (Uk = ${project.supplyContext.transformerUkPercent}%)`);

  yRight = drawKV(doc, col2X, yRight, isFr ? 'Stade de Contrôle :' : 'Inspection Stage:', stage);
  yRight = drawKV(doc, col2X, yRight, isFr ? 'Référence PV :' : 'Certificate Ref:', refCode);
  yRight = drawKV(doc, col2X, yRight, isFr ? 'Date d\'Édition :' : 'Issue Date:', today);
  yRight = drawKV(doc, col2X, yRight, isFr ? 'Ingénieur Signataire :' : 'Signing Engineer:', signerName);
  yRight = drawKV(doc, col2X, yRight, isFr ? 'Organisme de Contrôle :' : 'Inspection Body:', inspectionBureau);

  yPos = Math.max(yLeft, yRight) + 4;

  // ── Section: TGBT Electrical Ratings ───────────────────────────────────────
  yPos = drawSectionHeading(doc, isFr ? '2. Paramètres Électriques du TGBT' : '2. TGBT Electrical Ratings', yPos, COLORS.slate800);
  yPos += 3;

  yLeft = yPos;
  yRight = yPos;

  yLeft = drawKV(doc, col1X, yLeft, isFr ? 'Courant Nominal Incomer :' : 'Main Incomer Rating:', `${tgbtCurrentA} A`);
  yLeft = drawKV(doc, col1X, yLeft, 'Ui (V) / Uimp (kV):', `${ratedUiVolts} V / ${ratedUimpKv} kV`);
  yLeft = drawKV(doc, col1X, yLeft, isFr ? 'Jeu de barres :' : 'Busbar rating:', `${project.tgbt.ratedCurrentBusbarA} A`);
  yLeft = drawKV(doc, col1X, yLeft, 'Icw 1s / Ipk:', `${project.tgbt.shortCircuitIcwKa} kA / ${project.tgbt.peakWithstandIpkKa} kA`);

  yRight = drawKV(doc, col2X, yRight, isFr ? 'Forme de séparation :' : 'Form of separation:', project.tgbt.internalForm);
  yRight = drawKV(doc, col2X, yRight, isFr ? 'Classe de protection :' : 'Ingress protection:', `IP${project.tgbt.enclosureIpRating || '31'} / IK${project.tgbt.enclosureIkRating || '08'}`);
  yRight = drawKV(doc, col2X, yRight, isFr ? 'Couple de serrage :' : 'Torque (busbar bolts):', `${busbarBoltSize} → ${recommendedTorqueNm} N·m`);
  yRight = drawKV(doc, col2X, yRight, isFr ? 'Compensation réactive :' : 'PF correction bank:', `${project.tgbt.compensationBankKvar} kVAR auto`);

  yPos = Math.max(yLeft, yRight) + 4;

  // ── Section: Measured Test Results ─────────────────────────────────────────
  yPos = drawSectionHeading(doc, isFr ? '3. Résultats des Mesures Instrumentales' : '3. Instrumental Test Results', yPos, COLORS.emeraldDark);
  yPos += 3;

  // 3-column measurement result table
  const colW3 = (pageWidth(doc) - 20) / 3;

  const measurements = [
    {
      label:    isFr ? 'Résistance d\'Isolement (Riso)' : 'Insulation Resistance (Riso)',
      value:    `${measuredRisoMegaOhms} MΩ`,
      required: '≥ 1.0 MΩ  @  500V DC',
      norm:     'IEC 61439-1 §10.9 / §11.9',
      pass:     isInsulationCompliant,
    },
    {
      label:    isFr ? 'Continuité des Masses PE (Rpe)' : 'PE Bonding Continuity (Rpe)',
      value:    `${measuredRpeMilliOhms} mΩ`,
      required: '≤ 100 mΩ  @  ≥10 A',
      norm:     'IEC 61439-1 §10.8 / §11.8',
      pass:     isBondingCompliant,
    },
    {
      label:    isFr ? 'Essai Diélectrique' : 'Dielectric Withstand',
      value:    `${appliedDielectricKv} kV AC`,
      required: `≥ ${requiredDielectricVoltageKv} kV AC  /  ${dielectricWithstandSec}s`,
      norm:     'IEC 61439-1 §10.9.2 / §11.9.2',
      pass:     isDielectricCompliant,
    },
  ];

  measurements.forEach((m, i) => {
    const mx = 10 + i * colW3 + (i > 0 ? 2 : 0);
    const mw = colW3 - 2;
    const bg: [number, number, number] = m.pass ? COLORS.rowPass : COLORS.rowFail;

    setFillColor(doc, bg);
    setDrawColor(doc, m.pass ? COLORS.emerald : COLORS.rose);
    doc.roundedRect(mx, yPos, mw, 28, 2, 2, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    setTextColor(doc, COLORS.obsidian);
    const lines = doc.splitTextToSize(m.label, mw - 6);
    doc.text(lines, mx + mw / 2, yPos + 6, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    setTextColor(doc, m.pass ? COLORS.emerald : COLORS.rose);
    doc.text(m.value, mx + mw / 2, yPos + 15, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    setTextColor(doc, COLORS.slate600);
    doc.text(`Requis: ${m.required}`, mx + mw / 2, yPos + 21, { align: 'center' });
    doc.text(m.norm, mx + mw / 2, yPos + 25.5, { align: 'center' });
  });

  yPos += 33;

  // ── Section: Power Balance Summary ─────────────────────────────────────────
  yPos = drawSectionHeading(doc, isFr ? '4. Synthèse du Bilan de Puissance (NF C 15-100 §311)' : '4. Power Balance Summary (NF C 15-100 §311)', yPos);
  yPos += 3;

  yLeft = yPos;
  yRight = yPos;
  yLeft = drawKV(doc, col1X, yLeft, isFr ? 'Puissance Installée :' : 'Installed Power:', `${balance.installedPowerKw} kW (${balance.installedApparentKva} kVA)`);
  yLeft = drawKV(doc, col1X, yLeft, isFr ? 'Puissance Appelée :' : 'Demand Power:', `${balance.demandActivePowerKw} kW (${balance.demandApparentPowerKva} kVA)`);
  yLeft = drawKV(doc, col1X, yLeft, isFr ? 'Courant d\'Emploi TGBT :' : 'TGBT Design Current:', `Ib = ${tgbtCurrentA} A`);

  yRight = drawKV(doc, col2X, yRight, isFr ? 'Facteur de Puissance :' : 'Power Factor:', `cos φ = ${balance.averagePowerFactor}`);
  yRight = drawKV(doc, col2X, yRight, isFr ? 'Charge du Transformateur :' : 'Transformer Loading:', `${balance.transformerUtilizationPercent}%`);
  yRight = drawKV(doc, col2X, yRight, isFr ? 'Compensation Recommandée :' : 'Recommended Q corr.:', `${balance.recommendedCompensationKvar} kVAR`);

  yPos = Math.max(yLeft, yRight) + 8;

  // Final decision banner
  const bannerColor: [number, number, number] = isApproved ? [6, 78, 59] : [79, 7, 30];
  setFillColor(doc, bannerColor);
  doc.roundedRect(10, yPos, pageWidth(doc) - 20, 14, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  setTextColor(doc, COLORS.white);
  const decision = isApproved
    ? (isFr ? '✓  RÉCEPTION VALIDÉE SANS RÉSERVES — APTE À LA MISE SOUS TENSION' : '✓  COMMISSIONING APPROVED — FIT FOR ENERGIZATION')
    : (isFr ? '⚠  RÉCEPTION AJOURNÉE — LEVÉE DES RÉSERVES REQUISE AVANT MISE SOUS TENSION' : '⚠  COMMISSIONING PENDING — CORRECTIVE ACTIONS REQUIRED');
  doc.text(decision, pageWidth(doc) / 2, yPos + 9, { align: 'center' });

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 2 — Inspection Checklist Table (IEC 61439-1 §10 / §11)
  // ══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  drawPageHeader(doc, isFr ? 'LISTE DE CONTRÔLE — CEI 61439-1' : 'INSPECTION CHECKLIST — IEC 61439-1', projectRef, 2, TOTAL_PAGES);
  drawPageFooter(doc, locale);

  yPos = 30;

  yPos = drawSectionHeading(doc,
    isFr ? '5. Protocole d\'Inspection — Liste de Contrôle Normée' : '5. Inspection Protocol — Normative Checklist',
    yPos, COLORS.slate800);
  yPos += 3;

  // Category labels
  const catLabels: Record<InspectionCheckItem['category'], string> = {
    MECHANICAL:               isFr ? 'Mécanique / Enveloppe' : 'Mechanical / Enclosure',
    ELECTRICAL_CLEARANCES:    isFr ? 'Distances électriques' : 'Electrical Clearances',
    WIRING_TORQUE:            isFr ? 'Câblage / Serrage' : 'Wiring & Torque',
    INSULATION_DIELECTRIC:    isFr ? 'Isolement / Diélectrique' : 'Insulation & Dielectric',
    FUNCTIONAL_INTERLOCKS:    isFr ? 'Fonctionnel / Verrouillages' : 'Functional & Interlocks',
  };

  const tableBody = checklist.map((item) => [
    item.clauseIec,
    catLabels[item.category],
    isFr ? item.titleFr : item.titleEn,
    isFr ? item.criteriaFr : item.criteriaEn,
    item.measuredValue || '—',
    item.status,
  ]);

  autoTable(doc, {
    startY: yPos,
    margin: { left: 10, right: 10 },
    head: [[
      isFr ? 'Clause CEI' : 'IEC Clause',
      isFr ? 'Catégorie' : 'Category',
      isFr ? 'Point de Contrôle' : 'Check Point',
      isFr ? 'Critère d\'Acceptation' : 'Acceptance Criteria',
      isFr ? 'Valeur Mesurée' : 'Measured Value',
      isFr ? 'Décision' : 'Decision',
    ]],
    body: tableBody,
    theme: 'grid',
    styles: {
      fontSize: 7,
      cellPadding: 2.5,
      overflow: 'linebreak',
      textColor: COLORS.obsidian,
    },
    headStyles: {
      fillColor: COLORS.deepSlate,
      textColor: COLORS.white,
      fontStyle: 'bold',
      fontSize: 7.5,
    },
    columnStyles: {
      0: { cellWidth: 18, fontStyle: 'bold', halign: 'center' },
      1: { cellWidth: 28 },
      2: { cellWidth: 35 },
      3: { cellWidth: 55 },
      4: { cellWidth: 22, halign: 'center', fontStyle: 'bold' },
      5: { cellWidth: 22, halign: 'center', fontStyle: 'bold' },
    },
    willDrawCell: (data) => {
      if (data.section === 'body' && data.column.index === 5) {
        const status = data.cell.raw as string;
        if (status === 'PASS') {
          data.doc.setFillColor(236, 253, 245);
          data.doc.setTextColor(16, 185, 129);
        } else if (status === 'FAIL') {
          data.doc.setFillColor(255, 241, 242);
          data.doc.setTextColor(244, 63, 94);
        } else {
          data.doc.setFillColor(255, 251, 235);
          data.doc.setTextColor(245, 158, 11);
        }
      }
    },
    alternateRowStyles: { fillColor: COLORS.rowEven },
  });

  // Compliance summary row below table
  const finalY = (doc as any).lastAutoTable?.finalY ?? 180;

  yPos = finalY + 6;
  setFillColor(doc, COLORS.rowEven);
  setDrawColor(doc, COLORS.slate600);
  doc.roundedRect(10, yPos, pageWidth(doc) - 20, 12, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  setTextColor(doc, COLORS.obsidian);
  doc.text(
    `${isFr ? 'Résultat :' : 'Summary:'}  ${passCount} ${isFr ? 'conformes' : 'passed'}  ·  ${failCount} ${isFr ? 'non-conformes' : 'failed'}  ·  ${pendingCount} ${isFr ? 'en attente' : 'pending'}  ·  Taux: ${compliancePct}%`,
    pageWidth(doc) / 2,
    yPos + 8,
    { align: 'center' }
  );

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 3 — Regulatory Standards Matrix & Normative Traceability
  // ══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  drawPageHeader(doc, isFr ? 'MATRICE DE CONFORMITÉ NORMATIVE' : 'REGULATORY COMPLIANCE MATRIX', projectRef, 3, TOTAL_PAGES);
  drawPageFooter(doc, locale);

  yPos = 30;

  yPos = drawSectionHeading(doc,
    isFr ? '6. Matrice Multi-Normes de Conformité Réglementaire' : '6. Multi-Standard Regulatory Compliance Matrix',
    yPos, COLORS.slate800);
  yPos += 3;

  const regulatoryRows = [
    {
      std:     'NF C 15-100 §311 / IEC 60364-1',
      domain:  isFr ? 'Bilan de Puissance & Foisonnement' : 'Power Balance & Diversity',
      detail:  `S_dem = ${balance.demandApparentPowerKva} kVA — Cos φ = ${balance.averagePowerFactor} — Charge Transfo = ${balance.transformerUtilizationPercent}%`,
      result:  balance.transformerUtilizationPercent <= 100 ? 'PASS' : 'WARNING',
    },
    {
      std:     'NF C 15-100 §525 / IEC 60364-5-52',
      domain:  isFr ? 'Chutes de Tension ΔU%' : 'Voltage Drops ΔU%',
      detail:  isFr ? 'Limite éclairage ≤ 3%, force motrice ≤ 5% (origine installation)' : 'Limit: lighting ≤ 3%, power ≤ 5% (from origin)',
      result:  'PASS',
    },
    {
      std:     'IEC 60909 / NF EN 60909',
      domain:  isFr ? 'Courant de Court-Circuit (Icc3)' : 'Short-Circuit Current (Icc3)',
      detail:  `Icc3 ≈ ${Math.round(balance.installedApparentKva * 0.035)} kA — Icu TGBT ≥ 36 kA — Icw = ${project.tgbt.shortCircuitIcwKa} kA 1s`,
      result:  'PASS',
    },
    {
      std:     'IEC 61439-1 / IEC 61439-2',
      domain:  isFr ? 'Conception & Vérification TGBT' : 'TGBT Design & Verification',
      detail:  `${project.tgbt.internalForm} — IP${project.tgbt.enclosureIpRating || '31'}/IK${project.tgbt.enclosureIkRating || '08'} — Busbar ${project.tgbt.ratedCurrentBusbarA} A`,
      result:  'PASS',
    },
    {
      std:     'IEC 61439-1 §10.9 / §11.9',
      domain:  isFr ? 'Résistance d\'Isolement (Riso)' : 'Insulation Resistance (Riso)',
      detail:  `${measuredRisoMegaOhms} MΩ mesurés — Seuil requis ≥ 1.0 MΩ @ 500V DC`,
      result:  isInsulationCompliant ? 'PASS' : 'FAIL',
    },
    {
      std:     'IEC 61439-1 §10.9.2 / §11.9.2',
      domain:  isFr ? 'Essai Diélectrique (Utest)' : 'Dielectric Withstand (Utest)',
      detail:  `${appliedDielectricKv} kV AC appliqués / ${dielectricWithstandSec}s — Requis ≥ ${requiredDielectricVoltageKv} kV AC`,
      result:  isDielectricCompliant ? 'PASS' : 'FAIL',
    },
    {
      std:     'IEC 61439-1 §10.8 / §11.8',
      domain:  isFr ? 'Continuité de Terre PE (Rpe)' : 'PE Earth Bonding (Rpe)',
      detail:  `${measuredRpeMilliOhms} mΩ mesurés — Requis ≤ 100 mΩ @ courant ≥ 10 A`,
      result:  isBondingCompliant ? 'PASS' : 'FAIL',
    },
    {
      std:     'NF C 15-100 §534 / IEC 60364-5-53',
      domain:  isFr ? 'Protection SPD Surtensions' : 'SPD Surge Protection',
      detail:  isFr ? 'Parafoudre Type 1+2 Iimp ≥ 12.5 kA (10/350 µs) — Déconnecteur dédié coordonné' : 'Type 1+2 SPD Iimp ≥ 12.5 kA (10/350 µs) — Coordinated disconnector',
      result:  'PASS',
    },
    {
      std:     'NF C 15-100 Partie 6 / CONSUEL',
      domain:  isFr ? 'Visa Réglementaire CONSUEL' : 'CONSUEL Regulatory Approval',
      detail:  isFr ? 'Conformité globale aux §4.1–§8.2 NF C 15-100 Partie 6 vérifiée' : 'Full compliance with §4.1–§8.2 NF C 15-100 Part 6 verified',
      result:  isApproved ? 'PASS' : 'PENDING',
    },
  ];

  autoTable(doc, {
    startY: yPos,
    margin: { left: 10, right: 10 },
    head: [[
      isFr ? 'Référence Normative' : 'Standard Reference',
      isFr ? 'Domaine Technique' : 'Technical Domain',
      isFr ? 'Détail de la Vérification' : 'Verification Detail',
      isFr ? 'Décision' : 'Result',
    ]],
    body: regulatoryRows.map(r => [r.std, r.domain, r.detail, r.result]),
    theme: 'striped',
    styles: {
      fontSize: 7,
      cellPadding: 2.5,
      overflow: 'linebreak',
      textColor: COLORS.obsidian,
    },
    headStyles: {
      fillColor: COLORS.deepSlate,
      textColor: COLORS.white,
      fontStyle: 'bold',
      fontSize: 7.5,
    },
    columnStyles: {
      0: { cellWidth: 45, fontStyle: 'bold' },
      1: { cellWidth: 42 },
      2: { cellWidth: 75 },
      3: { cellWidth: 18, halign: 'center', fontStyle: 'bold' },
    },
    willDrawCell: (data) => {
      if (data.section === 'body' && data.column.index === 3) {
        const val = data.cell.raw as string;
        if (val === 'PASS')         { data.doc.setTextColor(16, 185, 129); }
        else if (val === 'FAIL')    { data.doc.setTextColor(244, 63, 94); }
        else if (val === 'WARNING') { data.doc.setTextColor(245, 158, 11); }
        else                        { data.doc.setTextColor(100, 116, 139); }
      }
    },
  });

  // ══════════════════════════════════════════════════════════════════════════
  // PAGE 4 — Digital Signature Block & Official Certification
  // ══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  drawPageHeader(doc, isFr ? 'CERTIFICATIONS & SIGNATURES' : 'CERTIFICATIONS & SIGNATURES', projectRef, 4, TOTAL_PAGES);
  drawPageFooter(doc, locale);

  yPos = 30;

  yPos = drawSectionHeading(doc,
    isFr ? '7. Déclaration de Conformité & Certification Officielle' : '7. Compliance Declaration & Official Certification',
    yPos, COLORS.slate800);
  yPos += 5;

  // Official declaration text
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  setTextColor(doc, COLORS.obsidian);

  const declarationText = isFr
    ? [
        `Nous soussignés, certifions que l'installation électrique basse tension objet du présent procès-verbal,`,
        `relative au projet "${project.name}" (Réf: ${refCode}), a fait l'objet d'un contrôle complet`,
        `conformément aux prescriptions des normes en vigueur, notamment :`,
        ``,
        `  • CEI 61439-1/2 — Conception, construction et vérification des tableaux BT`,
        `  • NF C 15-100 Partie 6 — Vérification initiale et périodique des installations électriques`,
        `  • CEI 60364-6 — Vérification des installations basse tension`,
        `  • Arrêté du 26/02/2003 relatif aux vérifications des installations électriques`,
        ``,
        `Les essais instrumentaux mentionnés ont été réalisés avec des appareils étalonnés traçables.`,
        `Les mesures sont conformes aux seuils exigés par les normes applicables.`,
      ]
    : [
        `We, the undersigned, certify that the low-voltage electrical installation covered by this certificate,`,
        `for project "${project.name}" (Ref: ${refCode}), has been subject to a comprehensive inspection`,
        `in accordance with the requirements of the applicable standards, including:`,
        ``,
        `  • IEC 61439-1/2 — Design, construction and verification of low-voltage switchgear assemblies`,
        `  • NF C 15-100 Part 6 — Initial and periodic verification of electrical installations`,
        `  • IEC 60364-6 — Verification of low-voltage electrical installations`,
        ``,
        `The instrumental tests listed herein were performed with calibrated, traceable test equipment.`,
        `All measurements are within the thresholds required by the applicable standards.`,
      ];

  declarationText.forEach(line => {
    doc.text(line, 12, yPos);
    yPos += 5;
  });

  yPos += 6;

  // ── Final Status Box ────────────────────────────────────────────────────────
  const statusColor: [number, number, number] = isApproved ? [6, 78, 59] : [79, 7, 30];
  setFillColor(doc, statusColor);
  doc.roundedRect(10, yPos, pageWidth(doc) - 20, 16, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  setTextColor(doc, COLORS.white);
  const statusLine1 = isApproved
    ? (isFr ? '✓  INSTALLATION CONFORME — RÉCEPTION PRONONCÉE' : '✓  INSTALLATION COMPLIANT — ACCEPTANCE GRANTED')
    : (isFr ? '⚠  RÉCEPTION CONDITIONNELLE — RÉSERVES EN COURS DE LEVÉE' : '⚠  CONDITIONAL ACCEPTANCE — RESERVATIONS TO BE CLEARED');
  doc.text(statusLine1, pageWidth(doc) / 2, yPos + 7, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  setTextColor(doc, [200, 255, 230]);
  const statusLine2 = isApproved
    ? (isFr ? 'Mise sous tension autorisée — Dossier archivé' : 'Energization authorized — Dossier archived')
    : (isFr ? 'Mise sous tension reportée jusqu\'à levée complète des réserves' : 'Energization deferred until all reservations are cleared');
  doc.text(statusLine2, pageWidth(doc) / 2, yPos + 13, { align: 'center' });

  yPos += 24;

  // ── Signature Grid ──────────────────────────────────────────────────────────
  yPos = drawSectionHeading(doc, isFr ? '8. Blocs de Signature Électronique' : '8. Electronic Signature Blocks', yPos, COLORS.slate800);
  yPos += 5;

  const sigBlocks = [
    {
      role:  isFr ? 'Ingénieur Signataire' : 'Signing Engineer',
      name:  signerName,
      title: signerRole,
      date:  today,
    },
    {
      role:  isFr ? 'Organisme de Contrôle' : 'Inspection Body',
      name:  inspectionBureau,
      title: isFr ? 'Bureau de Vérification Agréé' : 'Accredited Inspection Authority',
      date:  today,
    },
    {
      role:  isFr ? 'Maître d\'Ouvrage / Client' : 'Client / Project Owner',
      name:  '___________________________',
      title: isFr ? 'Représentant Autorisé' : 'Authorized Representative',
      date:  '_____ / _____ / __________',
    },
  ];

  const sigW = (pageWidth(doc) - 20 - 8) / 3;
  sigBlocks.forEach((sig, i) => {
    const sx = 10 + i * (sigW + 4);
    const sh = 55;

    setFillColor(doc, COLORS.rowEven);
    setDrawColor(doc, COLORS.slate600);
    doc.roundedRect(sx, yPos, sigW, sh, 2, 2, 'FD');

    // Role header
    setFillColor(doc, COLORS.deepSlate);
    doc.roundedRect(sx, yPos, sigW, 9, 2, 2, 'F');
    doc.rect(sx, yPos + 5, sigW, 4, 'F'); // bottom corners square
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    setTextColor(doc, COLORS.gold);
    doc.text(sig.role.toUpperCase(), sx + sigW / 2, yPos + 6, { align: 'center' });

    // Signature area
    setDrawColor(doc, COLORS.slate400);
    doc.line(sx + 6, yPos + 28, sx + sigW - 6, yPos + 28);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(6.5);
    setTextColor(doc, COLORS.slate400);
    doc.text(isFr ? '(Signature / Cachet)' : '(Signature / Stamp)', sx + sigW / 2, yPos + 32, { align: 'center' });

    // Name
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    setTextColor(doc, COLORS.obsidian);
    doc.text(sig.name, sx + sigW / 2, yPos + 39, { align: 'center' });

    // Title
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    setTextColor(doc, COLORS.slate600);
    doc.text(sig.title, sx + sigW / 2, yPos + 44, { align: 'center' });

    // Date
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    setTextColor(doc, COLORS.slate600);
    doc.text(`${isFr ? 'Date :' : 'Date:'}  ${sig.date}`, sx + sigW / 2, yPos + 51, { align: 'center' });
  });

  yPos += 65;

  // ── Normative References ────────────────────────────────────────────────────
  yPos = drawSectionHeading(doc, isFr ? '9. Références Normatives Applicables' : '9. Applicable Normative References', yPos, COLORS.slate800);
  yPos += 4;

  const norms = [
    ['IEC 61439-1:2011+A1:2020', isFr ? 'Ensembles d\'appareillage de puissance basse tension — Partie 1 : Règles générales' : 'Low-voltage switchgear and controlgear assemblies — Part 1: General rules'],
    ['IEC 61439-2:2011+A1:2021', isFr ? 'Ensembles d\'appareillage de puissance basse tension — Partie 2 : Ensembles sous enveloppe' : 'Low-voltage switchgear assemblies — Part 2: Power switchgear and controlgear assemblies'],
    ['NF C 15-100 (Ed. 2002+A3:2015)', isFr ? 'Installations électriques à basse tension — Partie 6: Vérification' : 'Low-voltage electrical installations — Part 6: Verification'],
    ['IEC 60364-6:2016', isFr ? 'Installations électriques dans les bâtiments — Partie 6 : Vérification' : 'Low-voltage electrical installations — Part 6: Verification'],
    ['IEC 60909-0:2016', isFr ? 'Courants de court-circuit dans les réseaux triphasés à courant alternatif' : 'Short-circuit currents in three-phase AC systems'],
    ['IEEE Std 80-2013', isFr ? 'Guide pour la mise à la terre de postes électriques AC' : 'Guide for safety in AC substation grounding'],
  ];

  norms.forEach(([ref, desc], idx) => {
    const ny = yPos + idx * 5;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    setTextColor(doc, COLORS.slate800);
    doc.text(`• ${ref}`, 12, ny);
    doc.setFont('helvetica', 'normal');
    setTextColor(doc, COLORS.slate600);
    doc.text(desc, 12 + 60, ny);
  });

  yPos += norms.length * 5 + 8;

  // ── EPEDE Watermark/Seal ────────────────────────────────────────────────────
  setFillColor(doc, COLORS.rowEven);
  setDrawColor(doc, COLORS.gold);
  doc.setLineWidth(0.6);
  doc.roundedRect(pageWidth(doc) / 2 - 35, yPos, 70, 14, 3, 3, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  setTextColor(doc, COLORS.gold);
  doc.text('EPEDE CERTIFIED', pageWidth(doc) / 2, yPos + 6, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  setTextColor(doc, COLORS.slate600);
  doc.text('Electronic Power Engineering Digital Environment', pageWidth(doc) / 2, yPos + 11, { align: 'center' });

  // ── Save PDF ────────────────────────────────────────────────────────────────
  const filename = `PV_${project.id.toUpperCase()}_${stage}_${revisionRef}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
