// src/components/transmission/SurgeImpedanceAndFerrantiLab.tsx
// EPEDE D03 - Surge Impedance Loading (SIL), St. Clair Loadability Curve & Ferranti Compensation Lab

import React, { useState, useMemo } from 'react';
import {
  Zap,
  Activity,
  Sliders,
  TrendingUp,
  AlertTriangle,
  CheckCircle2,
  Cpu,
  Layers,
  Sparkles,
  RefreshCw,
  Compass,
  ArrowRight,
  Info
} from 'lucide-react';

interface Props {
  locale: 'fr' | 'en';
}

interface VoltagePreset {
  nominalKv: number;
  label: string;
  defaultLmhPerKm: number; // mH/km
  defaultCnfPerKm: number; // nF/km
  defaultRohmPerKm: number; // ohm/km
  defaultBundle: string;
  typicalThermalLimitMw: number;
}

const VOLTAGE_PRESETS: VoltagePreset[] = [
  {
    nominalKv: 90,
    label: '90 kV (Sous-transport Régional)',
    defaultLmhPerKm: 1.25,
    defaultCnfPerKm: 9.5,
    defaultRohmPerKm: 0.104,
    defaultBundle: '1× Aster 320',
    typicalThermalLimitMw: 85
  },
  {
    nominalKv: 225,
    label: '225 kV (Dorsale RIS Cameroun)',
    defaultLmhPerKm: 1.05,
    defaultCnfPerKm: 11.2,
    defaultRohmPerKm: 0.058,
    defaultBundle: '2× Aster 570 (Faisceau Biphasé)',
    typicalThermalLimitMw: 450
  },
  {
    nominalKv: 400,
    label: '400 kV (Super-Réseau / Interconnexion)',
    defaultLmhPerKm: 0.95,
    defaultCnfPerKm: 12.8,
    defaultRohmPerKm: 0.032,
    defaultBundle: '3× Al-Acier 500 (Faisceau Triphasé)',
    typicalThermalLimitMw: 1400
  }
];

export const SurgeImpedanceAndFerrantiLab: React.FC<Props> = ({ locale }) => {
  const isFr = locale === 'fr';

  const [selectedVoltageIndex, setSelectedVoltageIndex] = useState<number>(1); // 225 kV default
  const [lineLengthKm, setLineLengthKm] = useState<number>(280); // 280 km (Nachtigal - Bekoko / West link)
  const [activeTransferMw, setActiveTransferMw] = useState<number>(150); // MW transfer
  const [shuntCompensationPercent, setShuntCompensationPercent] = useState<number>(50); // 50% shunt reactors
  const [seriesCompensationPercent, setSeriesCompensationPercent] = useState<number>(0); // 0% series capacitors

  const preset = VOLTAGE_PRESETS[selectedVoltageIndex];

  // Mathematical solver for SIL, Reactive Balance, Ferranti, and St. Clair curve
  const results = useMemo(() => {
    const U = preset.nominalKv; // kV
    const L_h_km = preset.defaultLmhPerKm * 1e-3; // H/km
    const C_f_km = preset.defaultCnfPerKm * 1e-9; // F/km
    const omega = 2 * Math.PI * 50; // 50 Hz rad/s

    // Surge Impedance Zc = sqrt(L / C) in Ohms
    const Zc = Math.sqrt(L_h_km / C_f_km);

    // Natural Power (Surge Impedance Loading) P_SIL = U^2 / Zc (in MW)
    const Psil = Math.pow(U, 2) / Zc;

    // Total line inductive reactance and capacitive admittance
    const X_L_total = omega * L_h_km * lineLengthKm * (1 - seriesCompensationPercent / 100);
    const B_C_total = omega * C_f_km * lineLengthKm;

    // Line current for given active power (assuming cos phi ~ 0.95)
    const powerFactor = 0.95;
    const S_mva = activeTransferMw / powerFactor;
    const I_amp = (S_mva * 1000) / (Math.sqrt(3) * U);

    // Inductive Reactive Power consumed by series inductance: Q_L = 3 * X_L * I^2
    const Q_L_consumed = (3 * X_L_total * Math.pow(I_amp, 2)) / 1e6; // Mvar

    // Capacitive Reactive Power generated by shunt capacitance: Q_C = 3 * B_C * V_ph^2 = B_C * U^2
    const Q_C_generated_uncompensated = B_C_total * Math.pow(U, 2); // Mvar
    const Q_shunt_reactors = Q_C_generated_uncompensated * (shuntCompensationPercent / 100);
    const Q_C_effective = Q_C_generated_uncompensated - Q_shunt_reactors;

    // Net reactive power of the line (Q_net = Q_L - Q_C)
    // If Q_net > 0: line absorbs vars (like an inductor, occurs when P > SIL)
    // If Q_net < 0: line generates vars (like a capacitor, occurs when P < SIL)
    const Q_net_uncompensated = Q_L_consumed - Q_C_generated_uncompensated;
    const Q_net_compensated = Q_L_consumed - Q_C_effective;

    // Ferranti Effect at no-load (I = 0)
    // Propagation constant beta = omega * sqrt(L * C) in rad/km
    const beta = omega * Math.sqrt(L_h_km * C_f_km);
    const beta_l = beta * lineLengthKm;
    
    // Exact Ferranti voltage rise ratio Vr / Vs = 1 / cos(beta * l)
    const ferrantiRiseRatioUncompensated = 1 / Math.cos(Math.min(1.4, beta_l));
    const ferrantiVoltageKvUncompensated = U * ferrantiRiseRatioUncompensated;
    const ferrantiDeltaKvUncompensated = ferrantiVoltageKvUncompensated - U;

    // With shunt compensation k_sh, effective beta is reduced
    const effectiveBetaL = beta_l * Math.sqrt(Math.max(0.01, 1 - shuntCompensationPercent / 100));
    const ferrantiRiseRatioCompensated = 1 / Math.cos(Math.min(1.4, effectiveBetaL));
    const ferrantiVoltageKvCompensated = U * ferrantiRiseRatioCompensated;
    const ferrantiDeltaKvCompensated = ferrantiVoltageKvCompensated - U;

    // St. Clair Loadability Limit for this distance
    // Short line (< 80 km): Thermal limit dominates (1.0 - 1.2 * Thermal)
    // Medium line (80 - 250 km): Voltage drop delta V <= 5% dominates
    // Long line (> 250 km): Steady-state rotor angle stability delta <= 35° dominates
    let stClairLimitFactor = 1.0;
    if (lineLengthKm <= 80) {
      stClairLimitFactor = 1.0; // Thermal
    } else if (lineLengthKm <= 250) {
      stClairLimitFactor = 1.0 - 0.45 * ((lineLengthKm - 80) / 170); // Voltage drop
    } else {
      // Stability: St. Clair curve falls toward 1.0 * SIL at 400-500 km
      stClairLimitFactor = 0.55 * Math.pow(250 / lineLengthKm, 0.8);
    }
    const maxStableTransferMw = Math.round(preset.typicalThermalLimitMw * stClairLimitFactor * (1 + seriesCompensationPercent / 100));

    return {
      Zc: Math.round(Zc * 10) / 10,
      Psil: Math.round(Psil),
      QL: Math.round(Q_L_consumed * 10) / 10,
      QC_raw: Math.round(Q_C_generated_uncompensated * 10) / 10,
      Q_reactors: Math.round(Q_shunt_reactors * 10) / 10,
      Q_net: Math.round(Q_net_compensated * 10) / 10,
      ferrantiUncompKv: Math.round(ferrantiVoltageKvUncompensated * 10) / 10,
      ferrantiCompKv: Math.round(ferrantiVoltageKvCompensated * 10) / 10,
      ferrantiDeltaKv: Math.round(ferrantiDeltaKvCompensated * 10) / 10,
      ferrantiPercent: Math.round(((ferrantiVoltageKvCompensated - U) / U) * 1000) / 10,
      maxStableTransferMw,
      isHeavyLoad: activeTransferMw > Psil,
      isLightLoad: activeTransferMw < Psil,
      isNearSil: Math.abs(activeTransferMw - Psil) <= 0.1 * Psil
    };
  }, [selectedVoltageIndex, lineLengthKm, activeTransferMw, shuntCompensationPercent, seriesCompensationPercent, preset]);

  return (
    <div className="space-y-6 font-mono">
      {/* Header Banner */}
      <div className="p-5 sm:p-6 rounded-2xl bg-gradient-to-br from-slate-900 via-indigo-950/40 to-slate-900 border border-indigo-800/40 shadow-xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-80 h-80 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 relative z-10">
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-indigo-500/15 text-indigo-300 border border-indigo-500/30">
                PILLIER 14 · THÉORIE DES LIGNES LONGUES & RÉGIME D'ONDE
              </span>
              <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-amber-500/15 text-amber-300 border border-amber-500/30">
                ST. CLAIR · FERRANTI · IMPÉDANCE D'ONDE
              </span>
            </div>
            <h2 className="text-xl sm:text-2xl font-bold text-white flex items-center gap-2">
              <TrendingUp className="w-6 h-6 text-indigo-400" />
              <span>
                {isFr
                  ? 'Laboratoire Puissance Naturelle (SIL), Courbe de St. Clair & Effet Ferranti'
                  : 'Surge Impedance Loading (SIL), St. Clair Curve & Ferranti Lab'}
              </span>
            </h2>
            <p className="text-xs text-slate-300 mt-1 max-w-3xl font-sans">
              {isFr
                ? 'Comprenez le comportement dynamique des corridors EHV : à charge naturelle (P = SIL), la ligne ne consomme ni ne produit de réactif (profil de tension plat). À vide, l\'effet Ferranti génère une surtension capacitive destructive compensée par inductances shunt.'
                : 'Master EHV long-line wave dynamics: at Surge Impedance Loading (P = SIL), line reactive power balances perfectly. Below SIL or at no-load, Ferranti capacitive overvoltages threaten equipment insulation unless mitigated by shunt reactors.'}
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-950/80 border border-slate-800 text-right shrink-0">
            <span className="text-[10px] text-slate-400 block">{isFr ? 'Puissance Naturelle (SIL)' : 'Surge Impedance Loading'}</span>
            <span className="text-xl font-black text-amber-400">{results.Psil} MW</span>
            <span className="text-[10px] text-slate-500 block">Zc = {results.Zc} Ω</span>
          </div>
        </div>
      </div>

      {/* Main Interactive Matrix */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
        
        {/* Left Column: Sliders & Controls (5 Cols) */}
        <div className="lg:col-span-5 space-y-4">
          
          {/* Voltage Preset Selector */}
          <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-3">
            <div className="text-xs font-bold text-indigo-400 flex items-center justify-between">
              <span>{isFr ? 'Palier de Tension & Conducteurs' : 'Voltage Level & Bundle'}</span>
              <span className="text-[10px] text-slate-500">50 Hz</span>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
              {VOLTAGE_PRESETS.map((vp, idx) => (
                <button
                  key={vp.nominalKv}
                  type="button"
                  onClick={() => setSelectedVoltageIndex(idx)}
                  className={`p-2.5 rounded-lg text-left text-xs transition-all border ${
                    selectedVoltageIndex === idx
                      ? 'bg-indigo-500/20 text-white border-indigo-500 font-bold'
                      : 'bg-slate-950 text-slate-400 border-slate-800 hover:border-slate-700'
                  }`}
                >
                  <div className="font-bold">{vp.nominalKv} kV</div>
                  <div className="text-[10px] text-slate-400 truncate">{vp.defaultBundle}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Line Length & Transfer Sliders */}
          <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-3.5">
            <div className="text-xs font-bold text-sky-400 flex items-center justify-between">
              <span>{isFr ? 'Paramètres d\'Exploitation de la Liaison' : 'Corridor Operating Parameters'}</span>
              <span className="text-[10px] text-slate-500">Longueur & Transit</span>
            </div>

            {/* Line Length Slider */}
            <div className="space-y-1 text-xs">
              <div className="flex justify-between text-slate-300">
                <span>{isFr ? 'Longueur de Ligne (L)' : 'Line Length (L)'} :</span>
                <span className="text-sky-400 font-bold">{lineLengthKm} km</span>
              </div>
              <input
                type="range"
                min="30"
                max="600"
                step="10"
                value={lineLengthKm}
                onChange={(e) => setLineLengthKm(parseInt(e.target.value))}
                className="w-full accent-sky-500 cursor-pointer"
              />
              <div className="flex justify-between text-[10px] text-slate-500">
                <span>30 km (Courte)</span>
                <span>280 km (Nachtigal-Littoral)</span>
                <span>600 km (Interco Nord)</span>
              </div>
            </div>

            {/* Active Power Transfer Slider */}
            <div className="space-y-1 text-xs">
              <div className="flex justify-between text-slate-300">
                <span>{isFr ? 'Transit Actif (P)' : 'Active Power Transfer (P)'} :</span>
                <span className="text-emerald-400 font-bold">{activeTransferMw} MW</span>
              </div>
              <input
                type="range"
                min="0"
                max={Math.round(preset.typicalThermalLimitMw * 1.2)}
                step="10"
                value={activeTransferMw}
                onChange={(e) => setActiveTransferMw(parseInt(e.target.value))}
                className="w-full accent-emerald-500 cursor-pointer"
              />
              <div className="flex justify-between text-[10px] text-slate-500">
                <span>0 MW (À vide / Enclenchement)</span>
                <span className="text-amber-400 font-bold">SIL: {results.Psil} MW</span>
                <span>{Math.round(preset.typicalThermalLimitMw)} MW (Plein transit)</span>
              </div>
            </div>
          </div>

          {/* Compensation Controls: Shunt Reactors & Series Capacitors */}
          <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-3.5">
            <div className="text-xs font-bold text-amber-400 flex items-center justify-between">
              <span>{isFr ? 'Systèmes de Compensation Réactive' : 'Reactive Compensation Equipment'}</span>
              <span className="text-[10px] text-slate-500">Inductances & Condensateurs</span>
            </div>

            {/* Shunt Reactors Slider */}
            <div className="space-y-1 text-xs">
              <div className="flex justify-between text-slate-300">
                <span>{isFr ? 'Taux de Compensation Shunt (Réactances)' : 'Shunt Compensation (Reactors)'} :</span>
                <span className="text-amber-400 font-bold">{shuntCompensationPercent}% ({results.Q_reactors} Mvar)</span>
              </div>
              <input
                type="range"
                min="0"
                max="100"
                step="5"
                value={shuntCompensationPercent}
                onChange={(e) => setShuntCompensationPercent(parseInt(e.target.value))}
                className="w-full accent-amber-500 cursor-pointer"
              />
              <div className="text-[10px] text-slate-400 font-sans">
                {isFr
                  ? 'Atténue les surtensions Ferranti à vide en absorbant le réactif capacitif de la ligne.'
                  : 'Suppresses no-load Ferranti overvoltages by absorbing line capacitive charging vars.'}
              </div>
            </div>

            {/* Series Capacitors Slider */}
            <div className="space-y-1 text-xs">
              <div className="flex justify-between text-slate-300">
                <span>{isFr ? 'Compensation Série (Condensateurs FSC)' : 'Series Compensation (FSC)'} :</span>
                <span className="text-cyan-400 font-bold">{seriesCompensationPercent}%</span>
              </div>
              <input
                type="range"
                min="0"
                max="70"
                step="5"
                value={seriesCompensationPercent}
                onChange={(e) => setSeriesCompensationPercent(parseInt(e.target.value))}
                className="w-full accent-cyan-500 cursor-pointer"
              />
              <div className="text-[10px] text-slate-400 font-sans">
                {isFr
                  ? 'Réduit la réactance apparente de la ligne pour repousser la limite de stabilité St. Clair.'
                  : 'Shrinks net line reactance, boosting steady-state rotor angle stability transfer limits.'}
              </div>
            </div>
          </div>

        </div>

        {/* Right Column: Calculations, Ferranti Gauge & St. Clair Analysis (7 Cols) */}
        <div className="lg:col-span-7 space-y-4">
          
          {/* Key Metric Cards */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            
            <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800 space-y-1">
              <span className="text-[10px] text-slate-400 block">{isFr ? 'Tension Ferranti (Extrémité)' : 'Ferranti Voltage (Open)'}</span>
              <div className={`text-lg font-bold ${results.ferrantiCompKv > preset.nominalKv * 1.1 ? 'text-rose-400' : 'text-emerald-400'}`}>
                {results.ferrantiCompKv} kV
              </div>
              <span className="text-[10px] text-slate-500 block">
                {results.ferrantiPercent > 0 ? `+${results.ferrantiPercent}% surtension` : 'Stable'}
              </span>
            </div>

            <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800 space-y-1">
              <span className="text-[10px] text-slate-400 block">{isFr ? 'Bilan Réactif Net (Q)' : 'Net Line Vars (Q)'}</span>
              <div className={`text-lg font-bold ${results.Q_net > 0 ? 'text-amber-400' : 'text-sky-400'}`}>
                {results.Q_net > 0 ? `+${results.Q_net} Mvar` : `${results.Q_net} Mvar`}
              </div>
              <span className="text-[10px] text-slate-500 block">
                {results.Q_net > 0 ? (isFr ? 'Consommateur (Inductif)' : 'Inductive Consumer') : (isFr ? 'Générateur (Capacitif)' : 'Capacitive Generator')}
              </span>
            </div>

            <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800 space-y-1">
              <span className="text-[10px] text-slate-400 block">{isFr ? 'Production Capacitive Brute' : 'Raw Capacitive Charging'}</span>
              <div className="text-lg font-bold text-sky-400">
                {results.QC_raw} Mvar
              </div>
              <span className="text-[10px] text-slate-500 block">
                {Math.round((results.QC_raw / lineLengthKm) * 100) / 100} Mvar/km
              </span>
            </div>

            <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800 space-y-1">
              <span className="text-[10px] text-slate-400 block">{isFr ? 'Limite Stabilité St. Clair' : 'St. Clair Stability Limit'}</span>
              <div className="text-lg font-bold text-emerald-400">
                {results.maxStableTransferMw} MW
              </div>
              <span className="text-[10px] text-slate-500 block">
                {lineLengthKm > 250 ? (isFr ? 'Stabilité angulaire' : 'Angle Stability') : (isFr ? 'Thermique / Chute U' : 'Thermal / Drop')}
              </span>
            </div>

          </div>

          {/* Operating State Diagnostic Banner */}
          <div className={`p-4 rounded-xl border text-xs ${
            results.isNearSil
              ? 'bg-emerald-500/10 border-emerald-500/40 text-emerald-300'
              : results.isLightLoad
              ? 'bg-sky-500/10 border-sky-500/40 text-sky-300'
              : 'bg-amber-500/10 border-amber-500/40 text-amber-300'
          }`}>
            <div className="font-bold flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4" />
              <span>
                {results.isNearSil
                  ? (isFr ? 'RÉGIME OPTIMAL : LIGNE À LA CHARGE NATURELLE (P ≈ SIL)' : 'OPTIMAL REGIME: SURGE IMPEDANCE LOADING (P ≈ SIL)')
                  : results.isLightLoad
                  ? (isFr ? 'RÉGIME SOUS-CHARGÉ (P < SIL) : COMPORTEMENT CAPACITIF' : 'UNDERLOADED REGIME (P < SIL): CAPACITIVE BEHAVIOR')
                  : (isFr ? 'RÉGIME SURCHARGÉ (P > SIL) : COMPORTEMENT INDUCTIF' : 'OVERLOADED REGIME (P > SIL): INDUCTIVE BEHAVIOR')}
              </span>
            </div>
            <p className="text-[11px] text-slate-300 mt-1 font-sans leading-relaxed">
              {results.isNearSil
                ? (isFr
                    ? `À ${activeTransferMw} MW, la puissance réactive capacitive générée par les conducteurs (${results.QC_raw} Mvar) compense exactement la puissance inductive consommée (${results.QL} Mvar). Le profil de tension est parfaitement plat d'un bout à l'autre de la ligne !`
                    : `At ${activeTransferMw} MW, capacitive reactive generation matches series inductive consumption perfectly. Voltage profile is uniformly flat across the corridor!`)
                : results.isLightLoad
                ? (isFr
                    ? `Le transit (${activeTransferMw} MW) est inférieur au SIL (${results.Psil} MW). La ligne injecte du réactif (${Math.abs(results.Q_net)} Mvar) vers les postes d'extrémités, provoquant une élévation de tension. L'enclenchement des réactances shunt (${results.Q_reactors} Mvar) est requis.`
                    : `Active load (${activeTransferMw} MW) is below SIL (${results.Psil} MW). Line injects net capacitive vars into substations, lifting busbar voltages. Shunt reactors are required to clamp Ferranti rise.`)
                : (isFr
                    ? `Le transit (${activeTransferMw} MW) dépasse le SIL (${results.Psil} MW). La ligne consomme plus de réactif (${results.QL} Mvar) qu'elle n'en produit. Cela crée une chute de tension importante qui nécessite un soutien par bancs de condensateurs ou compensateur synchrone.`
                    : `Transfer (${activeTransferMw} MW) exceeds SIL (${results.Psil} MW). Line series inductance consumes heavy reactive power, causing steep receiving voltage drop requiring capacitor banks or synchronous condensers.`)}
            </p>
          </div>

          {/* St. Clair Loading Theory Visual Explainer */}
          <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-3">
            <div className="flex items-center justify-between text-xs font-bold text-white">
              <span>{isFr ? 'Les 3 Régimes de la Courbe de St. Clair' : 'The 3 Regimes of St. Clair Curve'}</span>
              <span className="text-[10px] text-slate-500">IEEE Trans. PAS-72</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-xs">
              <div className={`p-3 rounded-lg border ${
                lineLengthKm <= 80 ? 'bg-indigo-950/30 border-indigo-500/60' : 'bg-slate-950 border-slate-800'
              }`}>
                <div className="text-indigo-400 font-bold">1. Lignes Courtes (&lt; 80 km)</div>
                <div className="text-[10px] text-slate-300 mt-1 font-sans">
                  <strong>Limite Thermique</strong> (I_max). Déterminée uniquement par l'échauffement des câbles et la flèche maximale au sol.
                </div>
              </div>

              <div className={`p-3 rounded-lg border ${
                lineLengthKm > 80 && lineLengthKm <= 250 ? 'bg-sky-950/30 border-sky-500/60' : 'bg-slate-950 border-slate-800'
              }`}>
                <div className="text-sky-400 font-bold">2. Lignes Moyennes (80 - 250 km)</div>
                <div className="text-[10px] text-slate-300 mt-1 font-sans">
                  <strong>Limite de Chute de Tension</strong> (ΔU ≤ 5%). Nécessite des condensateurs shunt ou régleurs en charge (OLTC).
                </div>
              </div>

              <div className={`p-3 rounded-lg border ${
                lineLengthKm > 250 ? 'bg-amber-950/30 border-amber-500/60' : 'bg-slate-950 border-slate-800'
              }`}>
                <div className="text-amber-400 font-bold">3. Lignes Longues (&gt; 250 km)</div>
                <div className="text-[10px] text-slate-300 mt-1 font-sans">
                  <strong>Stabilité Statique Rotorique</strong> (angle δ ≤ 35°). Le transit admissible chute vers la valeur SIL pour éviter la perte de synchronisme.
                </div>
              </div>
            </div>
          </div>

          {/* Industrial Benchmark: Cameroon Transmission Backbone */}
          <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2 text-xs">
            <div className="text-sky-400 font-bold flex items-center gap-1.5">
              <Sparkles className="w-4 h-4" />
              <span>{isFr ? 'Application Réelle au Réseau Interconnecté Camerounais (RIS & RIN)' : 'Real Field Application to Cameroon Grid (RIS & RIN)'}</span>
            </div>
            <p className="text-[11px] text-slate-300 leading-relaxed font-sans">
              {isFr ? (
                <>
                  Sur la liaison 225 kV <strong>Song Loulou → Mangombé → Bekoko</strong> (110 km) et le nouveau corridor <strong>Nachtigal → Bafoussam → Bamenda</strong> (240 km), SONATREL a déployé des <strong>inductances shunt de 20 Mvar</strong> à Bafoussam pour contenir l'effet Ferranti lors des délestages nocturnes ou déclenchements de ligne à vide, garantissant que la tension ne dépasse pas la valeur maximale admissible de service de <strong>245 kV</strong>.
                </>
              ) : (
                <>
                  On the 225 kV <strong>Song Loulou → Mangombé → Bekoko</strong> corridor and the <strong>Nachtigal → Bafoussam → Bamenda</strong> trunkline (240 km), utility SONATREL deployed <strong>20 Mvar shunt reactors</strong> at Bafoussam substation to contain Ferranti voltage excursions during light nocturnal load, guaranteeing that equipment never encounters voltages above the <strong>245 kV maximum continuous insulation limit</strong>.
                </>
              )}
            </p>
          </div>

        </div>

      </div>
    </div>
  );
};
