// src/components/calculators/modules/SilCalculator.tsx
import React, { useState } from 'react';
import { AlertTriangle } from 'lucide-react';

interface SilCalculatorProps {
  locale: 'fr' | 'en';
}

export const SilCalculator: React.FC<SilCalculatorProps> = ({ locale }) => {
  // 5. SURGE IMPEDANCE LOADING (SIL) & FERRANTI EFFECT (IEC 60071 / IEEE 738)
  const [silVoltageKv, setSilVoltageKv] = useState<number>(225); // 225 kV SONATREL standard
  const [silLengthKm, setSilLengthKm] = useState<number>(250); // 250 km transmission line
  const [silInductanceMhKm, setSilInductanceMhKm] = useState<number>(1.05); // mH/km typical HTB bundled
  const [silCapacitanceNfKm, setSilCapacitanceNfKm] = useState<number>(11.2); // nF/km typical HTB bundled

  // Calculations:
  // Zc = sqrt(L' / C') in Ohms
  const zcOhms = Math.sqrt((silInductanceMhKm * 1e-3) / (silCapacitanceNfKm * 1e-9));
  // P_SIL = Un^2 / Zc in MW
  const pSilMw = (silVoltageKv ** 2) / zcOhms;
  // Propagation velocity v = 1 / sqrt(L' * C') in km/s
  const vPhaseKmS = 1 / Math.sqrt((silInductanceMhKm * 1e-6) * (silCapacitanceNfKm * 1e-12));
  // Electrical angle theta = beta * L = omega * sqrt(L'*C') * L in radians
  const omega = 2 * Math.PI * 50; // 50 Hz Cameroon grid
  const betaRadKm = omega * Math.sqrt((silInductanceMhKm * 1e-3) * (silCapacitanceNfKm * 1e-9));
  const betaLRad = betaRadKm * silLengthKm;
  // Ferranti effect receiving end voltage at no-load (Ur = Us / cos(beta*L))
  const ferrantiFactor = 1 / Math.cos(betaLRad);
  const ferrantiReceivingVoltageKv = silVoltageKv * ferrantiFactor;
  const ferrantiRisePercent = (ferrantiFactor - 1) * 100;
  // Reactive power generated by line at no load Q_line = omega * C' * L * Un^2 in Mvar
  const qLineChargingMvar = omega * (silCapacitanceNfKm * 1e-9) * silLengthKm * (silVoltageKv ** 2);

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div className="lg:col-span-2 bg-[#0D1117] border border-[#252E38] rounded-2xl p-6 shadow-2xl space-y-6">
        <div className="text-xs font-mono font-bold text-[#F3F4F6] uppercase border-b border-[#252E38] pb-3 flex items-center justify-between">
          <span>{locale === 'fr' ? 'CALCUL DE CHARGE D\'ONDE (SIL) & EFFET FERRANTI HTB' : 'SURGE IMPEDANCE LOADING (SIL) & FERRANTI'}</span>
          <span className="text-cyan-400">P_SIL = Un² / Zc</span>
        </div>

        {/* Results Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 font-mono">
          <div className="bg-[#161C24] p-4 rounded-xl border border-cyan-500/40 space-y-1">
            <div className="text-[10px] text-neutral-400 uppercase">PUISSANCE NATURELLE (SIL)</div>
            <div className="text-2xl font-black text-cyan-300">
              {pSilMw.toFixed(1)} <span className="text-sm font-normal text-neutral-400">MW</span>
            </div>
            <div className="text-[10px] text-neutral-500">Transit sans réactif</div>
          </div>

          <div className="bg-[#161C24] p-4 rounded-xl border border-[#252E38] space-y-1">
            <div className="text-[10px] text-neutral-400 uppercase">IMPÉDANCE D'ONDE (Zc)</div>
            <div className="text-2xl font-black text-sky-400">
              {zcOhms.toFixed(1)} <span className="text-sm font-normal text-neutral-400">Ω</span>
            </div>
            <div className="text-[10px] text-neutral-500">Zc = √(L'/C')</div>
          </div>

          <div className="bg-[#161C24] p-4 rounded-xl border border-[#252E38] space-y-1">
            <div className="text-[10px] text-neutral-400 uppercase">SURTENSION FERRANTI</div>
            <div className={`text-2xl font-black ${ferrantiRisePercent > 10 ? 'text-red-400' : ferrantiRisePercent > 5 ? 'text-amber-400' : 'text-emerald-400'}`}>
              +{ferrantiRisePercent.toFixed(2)} <span className="text-sm font-normal text-neutral-400">%</span>
            </div>
            <div className="text-[10px] text-neutral-500">U_rec = {ferrantiReceivingVoltageKv.toFixed(1)} kV</div>
          </div>

          <div className="bg-[#161C24] p-4 rounded-xl border border-[#252E38] space-y-1">
            <div className="text-[10px] text-neutral-400 uppercase">CHARGE CAPACITIVE (Qc)</div>
            <div className="text-2xl font-black text-amber-300">
              {qLineChargingMvar.toFixed(1)} <span className="text-sm font-normal text-neutral-400">Mvar</span>
            </div>
            <div className="text-[10px] text-neutral-500">Génération à vide</div>
          </div>
        </div>

        {/* Ferranti Advisory Banner */}
        {ferrantiRisePercent > 5 && (
          <div className="p-4 rounded-xl bg-amber-950/40 border border-amber-800/60 flex items-start gap-3 text-xs font-mono">
            <AlertTriangle className="h-5 w-5 text-amber-400 shrink-0 mt-0.5" />
            <div className="space-y-1">
              <div className="font-bold text-amber-200 uppercase">
                {locale === 'fr' ? 'Effet Ferranti Significatif Détecté' : 'Significant Ferranti Voltage Rise'}
              </div>
              <p className="text-amber-300/90 leading-relaxed font-sans">
                {locale === 'fr'
                  ? `La ligne génère ${qLineChargingMvar.toFixed(1)} Mvar de puissance réactive capacitive à vide. Pour maintenir la tension réceptrice sous 245 kV (limite haute SONATREL HTB 225 kV), l'installation d'une inductance shunt de compensation d'environ ${(qLineChargingMvar * 0.75).toFixed(0)} Mvar est recommandée au poste d'extrémité.`
                  : `The line generates ${qLineChargingMvar.toFixed(1)} Mvar capacitive charging at no-load. To keep receiving end voltage within limits, a shunt compensation reactor rated ~${(qLineChargingMvar * 0.75).toFixed(0)} Mvar is recommended.`}
              </p>
            </div>
          </div>
        )}

        {/* Formula Reference */}
        <div className="bg-[#11161D] p-4 rounded-xl border border-[#252E38] text-xs font-mono space-y-2">
          <div className="text-cyan-400 font-bold uppercase text-[11px]">FORMULES ET NORMES APPLIQUÉES</div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-neutral-300">
            <div>
              <span className="text-neutral-500">Puissance naturelle (SIL) :</span>
              <div className="font-bold text-cyan-300 mt-0.5">P_SIL = Un² / Zc  (avec Zc = √(L'/C'))</div>
            </div>
            <div>
              <span className="text-neutral-500">Tension à vide (Ferranti) :</span>
              <div className="font-bold text-cyan-300 mt-0.5">U_rec = U_send / cos(β·L)</div>
            </div>
            <div>
              <span className="text-neutral-500">Puissance réactive de charge :</span>
              <div className="font-bold text-cyan-300 mt-0.5">Qc = ω · C' · L · Un²  (50 Hz)</div>
            </div>
            <div>
              <span className="text-neutral-500">Norme de référence :</span>
              <div className="font-bold text-white mt-0.5">CEI 60071-1 & IEEE Std 738</div>
            </div>
          </div>
        </div>
      </div>

      {/* Line Inputs */}
      <div className="bg-[#11161D] border border-[#252E38] rounded-2xl p-5 shadow-xl space-y-4 font-mono text-xs">
        <div className="text-[10px] text-neutral-400 uppercase font-bold border-b border-[#252E38] pb-2">
          PARAMÈTRES DE LA LIGNE HTB
        </div>

        <div className="space-y-1">
          <label className="text-neutral-300">Tension nominale Un (kV) :</label>
          <select
            value={silVoltageKv}
            onChange={(e) => setSilVoltageKv(parseFloat(e.target.value))}
            className="w-full bg-[#161C24] border border-[#252E38] rounded-lg px-3 py-2 text-cyan-300 font-bold focus:border-cyan-400 focus:outline-none"
          >
            <option value="225">225 kV (Réseau Transport HTB SONATREL)</option>
            <option value="90">90 kV (Sous-transport Régional SONATREL)</option>
            <option value="400">400 kV (Interconnexions Continentales WAPP/PEAC)</option>
            <option value="30">30 kV (Distribution MT Eneo)</option>
          </select>
        </div>

        <div className="space-y-1">
          <label className="text-neutral-300">Longueur de ligne L (km) :</label>
          <input
            type="number"
            value={silLengthKm}
            onChange={(e) => setSilLengthKm(parseFloat(e.target.value) || 1)}
            className="w-full bg-[#161C24] border border-[#252E38] rounded-lg px-3 py-2 text-cyan-300 font-bold focus:border-cyan-400 focus:outline-none"
          />
          <div className="flex flex-wrap gap-1.5 pt-1 text-[10px]">
            <button type="button" onClick={() => setSilLengthKm(100)} className="px-2 py-0.5 bg-[#161C24] hover:text-cyan-300 rounded border border-[#252E38]">100 km (Mangombé-Logbaba)</button>
            <button type="button" onClick={() => setSilLengthKm(280)} className="px-2 py-0.5 bg-[#161C24] hover:text-cyan-300 rounded border border-[#252E38]">280 km (Songloulou-Yaoundé)</button>
            <button type="button" onClick={() => setSilLengthKm(550)} className="px-2 py-0.5 bg-[#161C24] hover:text-cyan-300 rounded border border-[#252E38]">550 km (Nachtigal-Ngaoundéré)</button>
          </div>
        </div>

        <div className="space-y-1">
          <label className="text-neutral-300">Inductance linéique L' (mH/km) :</label>
          <input
            type="number"
            step="0.05"
            value={silInductanceMhKm}
            onChange={(e) => setSilInductanceMhKm(parseFloat(e.target.value) || 0.1)}
            className="w-full bg-[#161C24] border border-[#252E38] rounded-lg px-3 py-2 text-cyan-300 font-bold focus:border-cyan-400 focus:outline-none"
          />
        </div>

        <div className="space-y-1">
          <label className="text-neutral-300">Capacité linéique C' (nF/km) :</label>
          <input
            type="number"
            step="0.1"
            value={silCapacitanceNfKm}
            onChange={(e) => setSilCapacitanceNfKm(parseFloat(e.target.value) || 0.1)}
            className="w-full bg-[#161C24] border border-[#252E38] rounded-lg px-3 py-2 text-cyan-300 font-bold focus:border-cyan-400 focus:outline-none"
          />
        </div>
      </div>
    </div>
  );
};
